Running on uc2n003.localdomain
Date: Mo 13. Jan 14:29:11 CET 2025
Python version: Python 3.9.18
Environment: # conda environments:
#
new_env                  /home/ma/ma_ma/ma_tischuet/.conda/envs/new_env
base                     /opt/bwhpc/common/devel/miniconda/23.9.0-py3.9.15
                         /pfs/work7/workspace/scratch/ma_tischuet-team-project-hws-2024/envs/TP
                         /pfs/work7/workspace/scratch/ma_tischuet-team-project-hws-2024/envs/TP_general
                         /pfs/work7/workspace/scratch/ma_tischuet-team_project_explainable_deepfakes/envs/TP_backup
                      *  /pfs/work7/workspace/scratch/ma_tischuet-team_project_explainable_deepfakes/envs/TP_main
Traceback (most recent call last):
  File "/home/ma/ma_ma/ma_tischuet/Interpretable-Deep-Fake-Detection/preprocessing/rearrange.py", line 517, in <module>
    generate_dataset_file(dataset_name, dataset_root_path, output_file_path, comp, perturbation)
  File "/home/ma/ma_ma/ma_tischuet/Interpretable-Deep-Fake-Detection/preprocessing/rearrange.py", line 100, in generate_dataset_file
    with open(file=os.path.join(os.path.join(dataset_root_path, 'FaceForensics++', 'train.json')), mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_tischuet-team_project_explainable_deepfakes/datasets/rgb/FaceForensics++/train.json'

============================= JOB FEEDBACK =============================

NodeName=uc2n[003-006]
Job ID: 25136723
Cluster: uc2
User/Group: ma_tischuet/ma_ma
State: FAILED (exit code 1)
Nodes: 4
Cores per node: 80
CPU Utilized: 00:00:03
CPU Efficiency: 0.03% of 03:12:00 core-walltime
Job Wall-clock time: 00:00:36
Memory Utilized: 2.78 MB
Memory Efficiency: 0.00% of 195.31 GB
