Running on uc2n901.localdomain
Date: Mon Jan 20 13:13:20 CET 2025
Python version: Python 3.12.7
Environment: # conda environments:
#
TP_linux              *  /home/ma/ma_ma/ma_kreffert/.conda/envs/TP_linux
base                     /opt/bwhpc/common/devel/miniconda/23.9.0-py3.9.15
2025-01-20 13:13:23.328321: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-20 13:13:23.334226: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-20 13:13:23.342885: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1737375203.356542  439228 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1737375203.360674  439228 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-20 13:13:23.376671: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:root:Save log to ./logs/training/xception_2025-01-20-13-13-30
2025-01-20 13:13:30,558 - INFO - Save log to ./logs/training/xception_2025-01-20-13-13-30
INFO:root:--------------- Configuration ---------------
2025-01-20 13:13:30,559 - INFO - --------------- Configuration ---------------
INFO:root:Parameters: 
log_dir: ./logs/training/
pretrained: /home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/pretrained/xception-b5690688.pth
model_name: xception
backbone_name: xception
backbone_config: {'mode': 'original', 'num_classes': 2, 'inc': 3, 'dropout': False}
all_dataset: ['FaceForensics++', 'FF-F2F', 'FF-DF', 'FF-FS', 'FF-NT', 'FaceShifter', 'DeepFakeDetection', 'Celeb-DF-v1', 'Celeb-DF-v2', 'DFDCP', 'DFDC', 'DeeperForensics-1.0', 'UADFV']
train_dataset: ['FaceForensics++']
test_dataset: ['FaceForensics++', 'DeepFakeDetection']
compression: c40
train_batchSize: 32
test_batchSize: 32
workers: 8
frame_num: {'train': 32, 'test': 32}
resolution: 256
with_mask: False
with_landmark: False
use_data_augmentation: True
data_aug: {'flip_prob': 0.5, 'rotate_prob': 0.0, 'rotate_limit': [-10, 10], 'blur_prob': 0.5, 'blur_limit': [3, 7], 'brightness_prob': 0.5, 'brightness_limit': [-0.1, 0.1], 'contrast_limit': [-0.1, 0.1], 'quality_lower': 40, 'quality_upper': 100}
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]
optimizer: {'type': 'adam', 'adam': {'lr': 0.0002, 'beta1': 0.9, 'beta2': 0.999, 'eps': 1e-08, 'weight_decay': 0.0005, 'amsgrad': False}, 'sgd': {'lr': 0.0002, 'momentum': 0.9, 'weight_decay': 0.0005}}
lr_scheduler: None
nEpochs: 10
start_epoch: 0
save_epoch: 1
rec_iter: 100
logdir: ./logs
manualSeed: 1024
save_ckpt: True
save_feat: True
loss_func: cross_entropy
losstype: None
metric_scoring: auc
cuda: True
cudnn: True
mode: train
lmdb: False
dry_run: False
rgb_dir: 
lmdb_dir: ./datasets/lmdb
dataset_json_folder: preprocessing/dataset_json_v3
SWA: False
save_avg: True
label_dict: {'DFD_fake': 1, 'DFD_real': 0, 'FF-SH': 1, 'FF-F2F': 1, 'FF-DF': 1, 'FF-FS': 1, 'FF-NT': 1, 'FF-FH': 1, 'FF-real': 0, 'CelebDFv1_real': 0, 'CelebDFv1_fake': 1, 'CelebDFv2_real': 0, 'CelebDFv2_fake': 1, 'DFDCP_Real': 0, 'DFDCP_FakeA': 1, 'DFDCP_FakeB': 1, 'DFDC_Fake': 1, 'DFDC_Real': 0, 'DF_fake': 1, 'DF_real': 0, 'UADFV_Fake': 1, 'UADFV_Real': 0, 'roop_Real': 0, 'roop_Fake': 1}
local_rank: 0
ddp: False

2025-01-20 13:13:30,559 - INFO - Parameters: 
log_dir: ./logs/training/
pretrained: /home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/pretrained/xception-b5690688.pth
model_name: xception
backbone_name: xception
backbone_config: {'mode': 'original', 'num_classes': 2, 'inc': 3, 'dropout': False}
all_dataset: ['FaceForensics++', 'FF-F2F', 'FF-DF', 'FF-FS', 'FF-NT', 'FaceShifter', 'DeepFakeDetection', 'Celeb-DF-v1', 'Celeb-DF-v2', 'DFDCP', 'DFDC', 'DeeperForensics-1.0', 'UADFV']
train_dataset: ['FaceForensics++']
test_dataset: ['FaceForensics++', 'DeepFakeDetection']
compression: c40
train_batchSize: 32
test_batchSize: 32
workers: 8
frame_num: {'train': 32, 'test': 32}
resolution: 256
with_mask: False
with_landmark: False
use_data_augmentation: True
data_aug: {'flip_prob': 0.5, 'rotate_prob': 0.0, 'rotate_limit': [-10, 10], 'blur_prob': 0.5, 'blur_limit': [3, 7], 'brightness_prob': 0.5, 'brightness_limit': [-0.1, 0.1], 'contrast_limit': [-0.1, 0.1], 'quality_lower': 40, 'quality_upper': 100}
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]
optimizer: {'type': 'adam', 'adam': {'lr': 0.0002, 'beta1': 0.9, 'beta2': 0.999, 'eps': 1e-08, 'weight_decay': 0.0005, 'amsgrad': False}, 'sgd': {'lr': 0.0002, 'momentum': 0.9, 'weight_decay': 0.0005}}
lr_scheduler: None
nEpochs: 10
start_epoch: 0
save_epoch: 1
rec_iter: 100
logdir: ./logs
manualSeed: 1024
save_ckpt: True
save_feat: True
loss_func: cross_entropy
losstype: None
metric_scoring: auc
cuda: True
cudnn: True
mode: train
lmdb: False
dry_run: False
rgb_dir: 
lmdb_dir: ./datasets/lmdb
dataset_json_folder: preprocessing/dataset_json_v3
SWA: False
save_avg: True
label_dict: {'DFD_fake': 1, 'DFD_real': 0, 'FF-SH': 1, 'FF-F2F': 1, 'FF-DF': 1, 'FF-FS': 1, 'FF-NT': 1, 'FF-FH': 1, 'FF-real': 0, 'CelebDFv1_real': 0, 'CelebDFv1_fake': 1, 'CelebDFv2_real': 0, 'CelebDFv2_fake': 1, 'DFDCP_Real': 0, 'DFDCP_FakeA': 1, 'DFDCP_FakeB': 1, 'DFDC_Fake': 1, 'DFDC_Real': 0, 'DF_fake': 1, 'DF_real': 0, 'UADFV_Fake': 1, 'UADFV_Real': 0, 'roop_Real': 0, 'roop_Fake': 1}
local_rank: 0
ddp: False

['in_channels', 'out_channels', 'kernel_size', 'stride', 'padding', 'dilation', 'groups', 'bias', 'padding_mode', 'device', 'dtype']
spatial_count=0 keep_stride_count=0
[Errno 2] No such file or directory: '/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/preprocessing/dataset_json_v3/DeepFakeDetection.json'
Traceback (most recent call last):
  File "/pfs/data5/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/dataset/abstract_dataset.py", line 171, in collect_img_and_label_for_one_dataset
    with open(correct_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/preprocessing/dataset_json_v3/DeepFakeDetection.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/train.py", line 327, in <module>
    main()
  File "/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/train.py", line 285, in main
    test_data_loaders = prepare_testing_data(config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/train.py", line 154, in prepare_testing_data
    test_data_loaders[one_test_name] = get_test_data_loader(config, one_test_name)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/train.py", line 130, in get_test_data_loader
    test_set = DeepfakeAbstractBaseDataset(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pfs/data5/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/dataset/abstract_dataset.py", line 94, in __init__
    image_list, label_list, name_list = self.collect_img_and_label_for_one_dataset(one_data)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pfs/data5/home/ma/ma_ma/ma_kreffert/Interpretable-Deep-Fake-Detection/training/dataset/abstract_dataset.py", line 175, in collect_img_and_label_for_one_dataset
    raise ValueError(f'dataset {dataset_name} not exist!')
ValueError: dataset DeepFakeDetection not exist!

============================= JOB FEEDBACK =============================

NodeName=uc2n901
Job ID: 25161501
Cluster: uc2
User/Group: ma_kreffert/ma_ma
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:11
CPU Efficiency: 1.86% of 00:09:52 core-walltime
Job Wall-clock time: 00:00:37
Memory Utilized: 860.10 MB
Memory Efficiency: 1.72% of 48.83 GB
